// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ASHFUkr7EQlq6WbTQrgl7omB7CjpvjA',
    appId: '1:921892674774:web:ec8c063008ff7051e93d77',
    messagingSenderId: '921892674774',
    projectId: 'itrack-ff8cb',
    authDomain: 'itrack-ff8cb.firebaseapp.com',
    storageBucket: 'itrack-ff8cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6OWJsd4eweM3m94h762YvqnPscZ-9x8',
    appId: '1:921892674774:android:df25a60ae36a354fe93d77',
    messagingSenderId: '921892674774',
    projectId: 'itrack-ff8cb',
    storageBucket: 'itrack-ff8cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN4ib8n8mXy5KvvlSIM7T-4VBRbAz9lLw',
    appId: '1:921892674774:ios:57c84998203a1da8e93d77',
    messagingSenderId: '921892674774',
    projectId: 'itrack-ff8cb',
    storageBucket: 'itrack-ff8cb.appspot.com',
    iosBundleId: 'com.example.itrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN4ib8n8mXy5KvvlSIM7T-4VBRbAz9lLw',
    appId: '1:921892674774:ios:88689e995361de39e93d77',
    messagingSenderId: '921892674774',
    projectId: 'itrack-ff8cb',
    storageBucket: 'itrack-ff8cb.appspot.com',
    iosBundleId: 'com.example.itrack.RunnerTests',
  );
}
